name: Test Addition Function

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use the desired Python version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assumes you have a requirements.txt file

      # Step 4: Run addition function tests
      - name: Run Tests for Addition Function
        run: |
          python -m unittest discover -s . -p "test_addition.py"  # Run tests for the addition function

  deploy:
    needs: test  # Run this job after the tests
    runs-on: ubuntu-latest
    if: ${{ always() }}  # Always run the deploy job, even if tests fail

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Deploy Application
      - name: Deploy Application
        run: |
          echo "Deploying the application..."  # Replace with your actual deployment steps
