name: Test Addition Function

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Python Environment
      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install Dependencies (Directly without requirements.txt)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install unittest pytest

      # Step 4: Run Tests
      - name: Run Tests for Addition Function
        run: |
          python -m unittest discover -s . -p "test_addition.py"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ always() }}

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Deploy Application
      - name: Deploy Application
        run: |
          echo "Deploying the application..."
